[package]
name = "modrinth-cli"
version = "0.1.0"
edition = "2024"
description = "An easy-to-use, powerful Rust CLI to manage your local Minecraft instances and Modrinth mods"
authors = ["Paul8711 <contact@paul8711.com>"]
license = "AGPL-3.0-only"
repository = "https://github.com/paul8711-code/modrinth-cli"

[[bin]]
name = "mr"
path = "src/main.rs"

[dependencies]
clap = { version = "4.6.5", features = ["derive"] }
dialoguer = "0.12.0"
ferinth = { package = "paul8711-ferinth", git = "https://github.com/paul8711-code/ferinth.git" }
ratatui = "0.30.2"
tokio = { version = "1.53.1", features = ["full"] }
